course/urls.py
from django.urls import path
from course.views import ManageCourseListView, CourseCreateView, CourseUpdateView, CourseDeleteView, \
    CourseModuleUpdateView, ContentCreateUpdateView, ContentDeleteView, ModuleContentListView

app_name = 'course'

urlpatterns = [
    path(
        'mine/', ManageCourseListView.as_view(), name='course_list'),
    path(
        'create/', CourseCreateView.as_view(), name='course_create'),
    path(
        '<pk>/edit/', CourseUpdateView.as_view(), name='course_edit'),
    path(
        '<pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),
    path(
        '<pk>/module/', CourseModuleUpdateView.as_view(), name='course_module_update'),
    path(
        'module/<int:module_id>/content/<module_name>/create/', ContentCreateUpdateView.as_view(),
        name='module_content_create'),
    path(
        'module/<int:module_id>/content/<module_name>/<id>/', ContentCreateUpdateView.as_view(),
         name='module_content_update'),
    path(
        'content/<int:id>/delete/', ContentDeleteView.as_view(), name='module_content_delete'),
    path(
        'module/<int:module_id>', ModuleContentListView.as_view(), name='module_content_list'),

]

course/templates/course/delete.html
{% extends 'base.html' %}

{% block title %}
Usuń kurs
{% endblock %}

{% block content %}
    <ha>Usuń kurs "{{ object.title }}"</ha>
    <div class="module">
        <form action="" method="post">
            {% csrf_token %}
            <p>Czy na pewno chcesz usunąć kurs "{{ object }}"?</p>
            <input type="submit" class="button" value="Potwierdź">
        </form>
    </div>
{% endblock %}

course/templates/course/form.html
{% extends 'base.html' %}

{% block title %}
    {% if object %}
        Edytuj kurs {{ object.title }}
    {% else %}
        Utwórz nowy kurs
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% if object %}
            Edytuj kurs "{{ object.title }}"
        {% else %}
            Utwórz nowy kurs
        {% endif %}
    </h1>
    <div class="module">
        <h2>Informacja o kursie</h2>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Zapisz kurs"></p>
        </form>
    </div>
{% endblock %}

course/templates/course/list.html
{% extends 'base.html' %}

{% block title %}
Moje kursy
{% endblock %}

{% block content %}
    <h1>Moje kursy</h1>
    <div class="module">
        {% for course in object_list %}
            <div class="course-info">
                <h3>{{ course.title }}</h3>
                <p>
                    <a href="{% url 'course:course_edit' course.id %}">Edytuj</a>
                    <a href="{% url 'course:course_delete' course.id %}">Usuń</a>
                    <a href="{% url 'course:course_module_update' course.id %}">Edytuj moduły</a>
                        {% if course.modules.count > 0 %}
                            <a href="{% url 'course:module_content_list' course.modules.first.id %}">Zarządzaj treścią</a>
                        {% endif %}
                </p>
            </div>
        {% empty %}
            <p>Jeszcze nie utworzyłęś żadnych kursów</p>
        {% endfor %}
        <p>
            <a href="{% url 'course:course_create' %}" class="button">Utwórz nowy kurs</a>
        </p>
    </div>
{% endblock %}